### ISSUE TITLE
Eval#collapse causes endless loop

### ISSUE THREAD

**Issue by raulraja** [kategory/kategory#183] opened 2017-08-10 21:23 UTC
Noticed this while using `Traverse#sequence` which delegates to `foldRight` which uses `Eval`

```kotlin
fun <A> collapse(fa: Eval<A>): Eval<A> {
                var lfa = fa
                loop@ while (true) {
                    when (lfa) {
                        is Call -> {
                            lfa = lfa.thunk()
                        }
this case never returns or breaks -->     is Compute -> {
                            val clfa: Compute<A> = lfa
                            object : Compute<A>() {
                                override fun <S> start(): Eval<S> = clfa.start()
                                override fun <S> run(s: S): Eval<A> {
                                    lfa = clfa.run(s)
                                    return lfa
                                }
                            }
                        }
                        else -> break@loop
                    }
                }
                return lfa
            }
```

**Comment by pakoito** [comment] 2017-08-10 23:17
This is caused by the rewrite I did a while ago. Happy to get assigned to take a look.

**Comment by pakoito** [comment] 2017-08-11 00:26
I found the cause, but not why I did it. Tests still pass, so...great.

**Closed** 2017-08-11 11:44 UTC
Labels: bug
